### ISSUE TITLE
Passing multi-value parameters is parsed differently depending on environment

### ISSUE THREAD

**Issue by theetrain** [netlify/netlify-lambda#232] opened 2020-05-25 03:33 UTC
Hello, thanks for maintaining this tool.

When passing multi-value parameters to Netlify functions, they are parsed differently on local and production environments. 

For example, given the following request:

```
GET /.netlify/functions/getPets?pets=cat&pets=dog&pets=bird
```

The value of `event.queryStringParameters` on my **local environment** is:

```js
{
  "pets": ["cat", "dog", "bird"] // an array of strings
}
```

The value of `event.queryStringParameters` **when deployed to Netlify** is:

```js
{
  "pets": "cat, dog, bird" // a string with space-separated values
}
```

---

I prefer the format as it appears on my local environment. Unfortunately, I had to work around this inconsistency with my own brittle custom parser.

Local node version: v12.13.1
Netlify node version: v12.16.3
Potentially related: https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/

**Comment by erezrokah** [comment] 2020-08-02 14:59
This is somehow a duplicate of https://github.com/netlify/cli/issues/937.

Since `netlify-lambda serve` is [deprecated](https://github.com/netlify/netlify-lambda#netlify-lambda-serve-legacy-command) I'm closing this in favour of using the CLI.

If using the CLI+Netlify Lambda doesn't workout, please open an issue in the CLI repo.
Thanks 😄

**Closed by erezrokah** 2020-08-02 14:59 UTC
