### ISSUE TITLE
Async handlers produce unhandled promise rejection warnings

### ISSUE THREAD

**Issue by lloydh** [netlify/netlify-lambda#43] opened 2018-06-01 10:59 UTC
[Test Repo](https://github.com/lloydh/netlify-lambda-async-test)

I'm getting warnings about unhandled promise rejection when using async handler functions like below.

```javascript
exports.handler = async (event, context, callback) => {
  callback(null, {
    statusCode: 200,
    body: JSON.stringify({ success: true }),
  });
}
```

I've also tried using `Promise.Resolve()` with the response object.

```javascript
exports.handler = async (event, context, callback) => {
  Promise.resolve({
    statusCode: 200,
    body: JSON.stringify({ success: true }),
  });
}
```

My understanding is that either should work with node 8.10.x lambda instances but the netlify-lambda serve console produces the following warning:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined
    at callback (/Users/lloyd/dev/netlify-lambda-async-test/node_modules/netlify-lambda/lib/serve.js:22:42)
    at /Users/lloyd/dev/netlify-lambda-async-test/node_modules/netlify-lambda/lib/serve.js:41:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:56861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by mmiller42** [comment] 2018-06-13 13:50
When an async function throws an error, the function doesn't throw the error on its invocation, it rejects the promise it returns. However, AWS uses callbacks, not promises, so it doesn't read the return value of your function (which is the rejected promise).

You should try something like this:

```js
exports.handler = async (event, context, callback) => {
  try {
    // your logic here
   callback(null, result);
  } catch (err) {
    callback(err);
  }
};
```

Now you're explicitly passing any error that occurs to the callback, where Netlify/Lambda can actually read the error.

Your second example won't work, as Lambda doesn't use promises -- also, you have to make sure to `return` a promise from a function if you want it to be handled (but again, Lambda won't).

**Comment by i8ramin** [comment] 2018-10-14 18:59
I am also experiencing the same thing with my async callback. Even with the `try/catch` block. I put a console.log where the error is happening, and it looks like there are 2 requests happening for some reason. The first one succeeds, and the second one has an undefined `lambdaResponse`

```
Request from 108.27.71.64: GET /pr-merge

************** lambdaResponse { statusCode: 200, body: '' }
Response with status 200 in 472 ms.

************** lambdaResponse undefined
(node:3211) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined
    at callback (/app/node_modules/netlify-lambda/lib/serve.js:24:42)
    at /app/node_modules/netlify-lambda/lib/serve.js:43:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:3211) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have all my `async/await` functions surrounded by `try/catch` blocks and call `callback(err)` in the `catch` block.

**Comment by sw-yx** [comment] 2018-10-17 18:20
thanks @mmiller42, i actually didnt know that :)

hi @i8ramin - gonna close this as seems more to do with AWS lambda syntax than this `netlify-lambda` utility. hope you figure it out.

**Comment by nunoarruda** [comment] 2018-11-29 00:02
@sw-yx can you reopen this? I'm having the same issue as @lloydh and @i8ramin but @mmiller42 proposed solution does not solve the problem.

Here's my demo:

````Node
import fetch from "node-fetch";

exports.handler = async function(event, context, callback) {
    try {
        const response = await fetch("https://api.chucknorris.io/jokes/random");
        const data = await response.json();

        callback(null, {
            statusCode: 200,
            body: data.value
        });
    } catch (err) {
        console.error(err);
    }
};
````

Log:
````
netlify-lambda: Starting server
Lambda server is listening on 9000
Hash: 533f41e1d4248894ae20
Version: webpack 4.26.1
Time: 966ms
Built at: 11/28/2018 10:59:44 PM
  Asset      Size  Chunks             Chunk Names
test.js  18.3 KiB       0  [emitted]  test
Entrypoint test = test.js
[0] external "stream" 42 bytes {0} [built]
[1] external "zlib" 42 bytes {0} [built]
[2] external "url" 42 bytes {0} [built]
[3] external "http" 42 bytes {0} [built]
[4] external "https" 42 bytes {0} [built]
[5] ./test.js + 1 modules 40.8 KiB {0} [built]
    | ./test.js 1.14 KiB [built]
    | ../node_modules/node-fetch/lib/index.mjs 39.6 KiB [built]
Request from ::1: GET /test
Response with status 200 in 685 ms.
(node:99167) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined
    at callback (/Users/nunoarruda/Desktop/test/node_modules/netlify-lambda/lib/serve.js:22:42)
    at /Users/nunoarruda/Desktop/test/node_modules/netlify-lambda/lib/serve.js:41:21
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:99167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by 8eecf0d2** [comment] 2018-12-04 21:59
From the examples and logs I'm guessing the promise rejection is within **netlify-lambda**, and specifically the logic behind determining if a response / callback is a `Promise` or not.

Will have a go at fixing tonight.

**Comment by talves** [comment] 2018-12-05 01:16
@nunoarruda I answered this on [Stackoverflow for you](https://stackoverflow.com/questions/53583109/why-netlify-lambda-logs-an-unhandledpromiserejectionwarning-when-using-async-awa/53623756#53623756)

`node-fetch` uses a Promise, so you can dump the async/await

You want to make sure you check the response status, because your error will be tied to the response if it was a valid.

```
import fetch from "node-fetch";

const checkStatus = (res) => {
  if (res.ok) { // res.status >= 200 && res.status < 300
      return res.json();
  } else {
      throw new Error(res.statusText);
  }
}

exports.handler = function(event, context, callback) {
    fetch('https://api.chucknorris.io/jokes/random')
    .then(checkStatus)
    .then(response =>{
      // console.log('response:', response)
      callback(null, {
        statusCode: 200,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(response)
      });
    })
    .catch(error => {
      // console.log('error:', error.message)
      callback(error);
    })
};

```

**Comment by talves** [comment] 2018-12-05 01:55
[AWS lambda-functions did not support async/await unless Node 8.10](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/). Netlify is defaulting to version 8.10 based on the docs for new functions.

My build runtime was using node v6.15.1, but I am assuming this is different than the AWS_LAMBDA_JS_RUNTIME version. Would that affect the use of the `async` function?

**Comment by talves** [comment] 2018-12-05 02:45
@nunoarruda at first I was seeing the same error, but can't reproduce it, so my assumptions were incorrect.

**Comment by talves** [comment] 2018-12-05 19:42
I was able to remove the error message locally using the code below without using the callback:

```
import fetch from "node-fetch";

exports.handler = async function(event, context) {
    try {
        const response = await fetch("https://api.chucknorris.io/jokes/random");
        if (!response.ok) { // NOT res.status >= 200 && res.status < 300
            return { statusCode: response.status, body: response.statusText };
        }
        const data = await response.json();

        return {
            statusCode: 200,
            body: data.value
            // if you want to return whole json string
            // headers: { 'Content-Type': 'application/json' },
            // body: JSON.stringify(data)
        };
    } catch (err) {
        console.log(err); // output to netlify function log
        return {
            statusCode: 500,
            body: err.message // Could be a custom message or object i.e. JSON.stringify(err)
        };
    }
};
```

This is the way the CLI is handling the code in the callback using `callback(err)` more or less anyway.

**Comment by talves** [comment] 2018-12-06 01:49
@sw-yx Shawn, I don't think we should be using callback with the two handler types above in the previous comment, but I was hoping someone at Netlify could confirm this for me.

**Comment by sw-yx** [comment] 2018-12-06 09:59
i think you are correct Tony. [the docs indicate the same thing](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html)

i'm sadly far from a lambda expert. just trying to help maintain things as an employee with commit rights and a heavy user :) this thread has taught me something.

**Comment by talves** [comment] 2018-12-06 14:03
Ok, so maybe we can come up with a solution based on a  check that spits out a warning. 

```
function createCallback(response) {
  return function callback(err, lambdaResponse) {
    if (err) {
      return handleErr(err, response);
    }

    // ***Checking for a callback without err AND without lambdaResponse***
    if (!lambdaResponse || !lambdaResponse.statusCode) {
      // Handle the error condition when no pending response
    }

    response.statusCode = lambdaResponse.statusCode;
    for (const key in lambdaResponse.headers) {
      response.setHeader(key, lambdaResponse.headers[key]);
    }
    response.write(
      lambdaResponse.isBase64Encoded
        ? Buffer.from(lambdaResponse.body, "base64")
        : lambdaResponse.body
    );
    response.end();
  }
}

```

**Comment by sw-yx** [comment] 2018-12-06 14:41
ah i see @talves you want a nicer error message? sure I could do that. whats a nice error message? something like this?

```js
    // ***Checking for a callback without err AND without lambdaResponse***
    if (!lambdaResponse) {
      throw new Error('No response detected from your handler lambda. You may have forgotten to call `callback` or return a Promise.')
    }
	if (!lambdaResponse.statusCode) {
		throw new Error('No statusCode detected in your handler lambda. You may have forgotten to return an object with a defined statusCode (usually 200 for success) in your `callback`.')
	}
```

**Comment by talves** [comment] 2018-12-06 15:00
Yeah, those may work. Do we need to check for a pending response before we throw the error. Let me test this out because it would end up throwing the same error. Maybe we could just put a `response.end()` before we throw the errors.

**Comment by sw-yx** [comment] 2018-12-06 15:10
not sure what you mean by "throwing the same error" but i'll leave this open if you wanna send in a PR :)

**Comment by talves** [comment] 2018-12-06 15:12
It might take me awhile to get to, but yeah, I will take a look.

Also, I did a promise example for the CRA https://github.com/netlify/create-react-app-lambda/pull/17

**Comment by talves** [comment] 2018-12-06 15:41
@sw-yx I confirmed my statement about the warning when you use `callback` with an `async` handler

```
Request from ::1: GET /joke
Type of Promise: function function
err: null
lambdaResponse undefined
(node:640) UnhandledPromiseRejectionWarning: Error: No response detected from your handler lambda. You may have forgotten to call `callback` or return a Promise.
    at callback (D:\Git\Netlify\lambda-functions\test-site\node_modules\netlify-lambda\lib\serve.js:27:9)
    at D:\Git\Netlify\lambda-functions\test-site\node_modules\netlify-lambda\lib\serve.js:54:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
response: { category: null,
  icon_url: 'https://assets.chucknorris.host/img/avatar/chuck-norris.png',
  id: 'v6Wo1N4KQQqvVeDBoSNiCg',
  url: 'https://api.chucknorris.io/jokes/v6Wo1N4KQQqvVeDBoSNiCg',
  value: 'Go to Joke #51, for this joke. This was hacked by Chuck Norris.' }
err: null
lambdaResponse { statusCode: 200,
  headers: { 'Content-Type': 'application/json' },
  body: '{"category":null,"icon_url":"https://assets.chucknorris.host/img/avatar/chuck-norris.png","id":"v6Wo1N4KQQqvVeDBoSNiCg","url":"https://api.chucknorris.io/jokes/v6Wo1N4KQQqvVeDBoSNiCg","value":"Go to Joke #51, for this joke. This was hacked by Chuck Norris."}' }
Response with status 200 in 946 ms.
```

Throwing the error without handling the response gives the warning but also returns the error message we throw. I will have to look at this when I get time.

**Comment by sw-yx** [comment] 2018-12-06 16:51
soo ok tell me what to do

**Comment by talves** [comment] 2018-12-06 17:01
We need to test 2 conditions at minimum:

- Making the callback without any values (err, response), I think this will be handled
- Calling an `ansync` handler and returning the callback.

I am not sure what to do, until I am sure that all entry points on the handler are tested because I do not want to introduce false messages to the developer.

**Comment by waynehoover** [comment] 2018-12-28 03:49
Would love to test my async functions with netlify-lambda but this is currently blocking me. Just wanted to say thanks for any and all improvements.

**Comment by talves** [comment] 2018-12-28 15:05
Async functions are not blocked. Use my previous example as the correct way
to use them with NO callbacks. Callbacks are NOT valid with async
functions. We are leaving this issue open to decide how to proceed with
error messages when they are not setup correctly.

**Comment by sw-yx** [comment] 2018-12-28 16:56
i think Wayne deleted his comment after realizing async functions are fine. we even include an example for it in https://github.com/netlify/create-react-app-lambda now.

i'll try to make a note in the Readme since this seems a common issue

**Comment by waynehoover** [comment] 2018-12-29 02:20
I can deploy fine with async functions but when running locally with netlify-lambda serve I get this error:

```(node:26997) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type undefined
    at write_ (_http_outgoing.js:607:11)
    at ServerResponse.write (_http_outgoing.js:579:10)
    at callback (/Users/.../node_modules/netlify-lambda/lib/serve.js:26:14)
    at /Users/.../node_modules/netlify-lambda/lib/serve.js:41:21
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:26997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26997) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Hash: ec967454cf2cf833f214```

**Comment by talves** [comment] 2018-12-29 02:34
Try adding a body value with at least an empty string. I am curious if that is the type that is undefined.

**Comment by waynehoover** [comment] 2018-12-29 02:37
@talves, that fixes the error, thanks.

**Comment by sidati** [comment] 2019-02-22 00:11
Any progress on this one ? 😄

**Comment by romseguy** [comment] 2019-03-04 22:46
Same problem and resolved by removing `callback` here https://github.com/netlify/netlify-faunadb-example/blob/master/functions/todos-read-all.js#L21

**Closed** 2019-03-05 19:21 UTC
