### ISSUE TITLE
Running `serve` overwrites original lambda

### ISSUE THREAD

**Issue by kchung** [netlify/netlify-lambda#18] opened 2018-03-31 20:52 UTC
When running `netlify-lambda serve functions/`, the command keeps compiling the functions infinitely, bloating and overwriting the original files with every compilation.

I ran the command in the [code-examples repo](https://github.com/netlify/code-examples/tree/master/function_examples/random-word), notice the filesize growing bigger and bigger.

```
$ ./node_modules/.bin/netlify-lambda serve functions/
Starting server
Lambda server is listening on 9000
Hash: da984e20aebc1ac3f751
Version: webpack 3.11.0
Time: 431ms
    Asset     Size  Chunks             Chunk Names
random.js  2.98 kB       0  [emitted]  random
   [0] ./functions/random.js 424 bytes {0} [built]
Hash: 7369ba5e43bd2af7c5a1
Version: webpack 3.11.0
Time: 23ms
    Asset     Size  Chunks             Chunk Names
random.js  5.74 kB       0  [emitted]  random
   [0] ./functions/random.js 3.18 kB {0} [built]
Hash: f6e8fafb802d3919efd1
Version: webpack 3.11.0
Time: 16ms
    Asset     Size  Chunks             Chunk Names
random.js  8.68 kB       0  [emitted]  random
   [0] ./functions/random.js 6.12 kB {0} [built]
Hash: 77035ca7b401471403d9
Version: webpack 3.11.0
Time: 21ms
    Asset     Size  Chunks             Chunk Names
random.js  11.8 kB       0  [emitted]  random
   [0] ./functions/random.js 9.23 kB {0} [built]
Hash: b5edcfb7c37f7dd11bb8
Version: webpack 3.11.0
Time: 22ms
    Asset     Size  Chunks             Chunk Names
random.js  15.1 kB       0  [emitted]  random
   [0] ./functions/random.js 12.5 kB {0} [built]
Hash: 1ed77f22dbd1c977cbb5
Version: webpack 3.11.0
Time: 24ms
    Asset     Size  Chunks             Chunk Names
random.js  18.6 kB       0  [emitted]  random
   [0] ./functions/random.js 16 kB {0} [built]
Hash: c997d31cc2030de2d4a6
Version: webpack 3.11.0
Time: 20ms
    Asset     Size  Chunks             Chunk Names
random.js  22.2 kB       0  [emitted]  random
   [0] ./functions/random.js 19.6 kB {0} [built]

...
```

The original function files are also modified, see running `git status` right after `serve`:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   functions/random.js
```

`random.js` is overwritten with compiled code. This is with the package `netlify-lambda@0.2.0`.

**Comment by ahmedelgabri** [comment] 2018-04-01 19:11
I think this is a duplicate of https://github.com/netlify/netlify-lambda/issues/8

**Closed** 2018-04-02 16:30 UTC
